services:
  database:
    container_name: postgres
    image: postgres:16.1-alpine3.19
    ports:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - ft_transcendence

  frontend:
    container_name: frontend
    build:
      context: frontend
      target: prod
    ports:
      - 80:80
    env_file:
      - .env
    networks:
      - ft_transcendence

  backend:
    container_name: backend
    build:
      context: backend
      target: prod
      args:
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - 3001:3001
    env_file:
      - .env
    networks:
      - ft_transcendence
    depends_on:
      - database

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge

volumes:
  postgres:
    name: postgres-database
