services:
  database:
    container_name: postgres
    image: postgres:16.1-alpine3.19
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - ft_transcendence

  frontend:
    container_name: frontend
    build:
      context: frontend
      target: dev
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - ft_transcendence
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    container_name: backend
    build:
      context: backend
      target: dev
    ports:
      - 3001:3001
      - 5555:5555 # prisma studio
    env_file:
      - .env
    networks:
      - ft_transcendence
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge

volumes:
  postgres:
    name: postgres-database
